version: '3.7'

services:
  ui:
    build:
      context: .
      target: ui-dev
    volumes:
      - .:/app:cached
    ports:
      - 8000:8000
      - 0.0.0.0:8080:8080
    environment:
      - CHOKIDAR_USEPOLLING=true

