# This is a basic workflow to help you get started with Actions

name: ssh test

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  # Currently disabled to only trigger manually for testing
  # push:
  #   branches: [master]
  # pull_request:
  #   branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      # - name: Adding Known Hosts
      #   run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      # - name: Setup SSH
      #   uses: kielabokkie/ssh-key-and-known-hosts-action@v1
      #   with:
      #     ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     ssh-host: ${{ secrets.SSH_HOST }}

      # - name: Create SSH key
      #   run: |
      #     mkdir -p ~/.ssh/
      #     echo "$SSH_PRIVATE_KEY" > ../private.key
      #     sudo chmod 600 ../private.key
      #     echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
      #   shell: bash
      #   env:
      #     SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
      #     SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
      #     SSH_KEY_PATH: ${{ github.workspace }}/../private.key
      # - name: SSH
      #   run: ssh -i ${{ github.workspace }}/../private.key ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} ls -a apps/appv3.beep.nl/public
      - run: ls ./home/runner/.ssh
      - name: SSH
        run: ssh -i ./home/runner/.ssh/id_rsa ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} ls -a apps/appv3.beep.nl/public
